# Site settings
title: Reading Emergent Strategy
email: your-email@domain.com
url: https://example.github.io
description: "We're reading Emergent Strategy in preparation for Adrienne Maree Brown joining us in Boston mid-November. If you're interested in reading along with us, read on."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/GroupThatLuanaMakes
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  # - title: github
  #   url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
